# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Finance
    url: finance/
    weight: 20
  - name: Economics
    url: economics/
    weight: 25
  - name: Career
    url: career/
    weight: 30
  - name: Study
    url: study/
    weight: 35
  - name: Watches
    url: watches/
    weight: 40
  - name: Others
    url: others/
    weight: 50
